version: "3.3"

services:
  sd_db:
    image: nouchka/sqlite3
    volumes:
      - db.sqlite3:/var/lib/sqlite/data/
  sd_web:
    build: .
    command: python /usr/src/django_library/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/django_library
    ports:
      - "8000:8000"
    depends_on:
      - sd_db
volumes:
  db.sqlite3:
